language: python
sudo: false
python:
- '3.5'

addons:
  postgresql: "9.4"

before_script:
- export DATABASE_URL=postgres://postgres@localhost/askcoding
- export DJANGO_SECRET=`openssl rand -hex 64`
- psql -c "CREATE DATABASE askcoding;" -U postgres


install:
  - pip install -r requirements.txt

script:
- flake8
- py.test -v

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
